# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bike.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/bike.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/bike.proto\x12\x08tutorial\" \n\x0emobile_request\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"J\n\x0fmobile_response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05icode\x18\x02 \x01(\x05\x12\x11\n\x04\x64\x61ta\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data\".\n\rlogin_request\x12\x0e\n\x06mobile\x18\x01 \x01(\t\x12\r\n\x05icode\x18\x02 \x01(\x05\";\n\x0elogin_response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"?\n\x0eunlock_request\x12\x0e\n\x06mobile\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65v_no\x18\x02 \x01(\x05\x12\r\n\x05token\x18\x03 \x01(\t\"-\n\x0funlock_response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\tb\x06proto3'
)




_MOBILE_REQUEST = _descriptor.Descriptor(
  name='mobile_request',
  full_name='tutorial.mobile_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile', full_name='tutorial.mobile_request.mobile', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=63,
)


_MOBILE_RESPONSE = _descriptor.Descriptor(
  name='mobile_response',
  full_name='tutorial.mobile_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tutorial.mobile_response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icode', full_name='tutorial.mobile_response.icode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='tutorial.mobile_response.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_data', full_name='tutorial.mobile_response._data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=65,
  serialized_end=139,
)


_LOGIN_REQUEST = _descriptor.Descriptor(
  name='login_request',
  full_name='tutorial.login_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile', full_name='tutorial.login_request.mobile', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icode', full_name='tutorial.login_request.icode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=187,
)


_LOGIN_RESPONSE = _descriptor.Descriptor(
  name='login_response',
  full_name='tutorial.login_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tutorial.login_response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='tutorial.login_response.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='tutorial.login_response.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=248,
)


_UNLOCK_REQUEST = _descriptor.Descriptor(
  name='unlock_request',
  full_name='tutorial.unlock_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobile', full_name='tutorial.unlock_request.mobile', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dev_no', full_name='tutorial.unlock_request.dev_no', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='tutorial.unlock_request.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=313,
)


_UNLOCK_RESPONSE = _descriptor.Descriptor(
  name='unlock_response',
  full_name='tutorial.unlock_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tutorial.unlock_response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='tutorial.unlock_response.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=360,
)

_MOBILE_RESPONSE.oneofs_by_name['_data'].fields.append(
  _MOBILE_RESPONSE.fields_by_name['data'])
_MOBILE_RESPONSE.fields_by_name['data'].containing_oneof = _MOBILE_RESPONSE.oneofs_by_name['_data']
DESCRIPTOR.message_types_by_name['mobile_request'] = _MOBILE_REQUEST
DESCRIPTOR.message_types_by_name['mobile_response'] = _MOBILE_RESPONSE
DESCRIPTOR.message_types_by_name['login_request'] = _LOGIN_REQUEST
DESCRIPTOR.message_types_by_name['login_response'] = _LOGIN_RESPONSE
DESCRIPTOR.message_types_by_name['unlock_request'] = _UNLOCK_REQUEST
DESCRIPTOR.message_types_by_name['unlock_response'] = _UNLOCK_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mobile_request = _reflection.GeneratedProtocolMessageType('mobile_request', (_message.Message,), {
  'DESCRIPTOR' : _MOBILE_REQUEST,
  '__module__' : 'protos.bike_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.mobile_request)
  })
_sym_db.RegisterMessage(mobile_request)

mobile_response = _reflection.GeneratedProtocolMessageType('mobile_response', (_message.Message,), {
  'DESCRIPTOR' : _MOBILE_RESPONSE,
  '__module__' : 'protos.bike_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.mobile_response)
  })
_sym_db.RegisterMessage(mobile_response)

login_request = _reflection.GeneratedProtocolMessageType('login_request', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN_REQUEST,
  '__module__' : 'protos.bike_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.login_request)
  })
_sym_db.RegisterMessage(login_request)

login_response = _reflection.GeneratedProtocolMessageType('login_response', (_message.Message,), {
  'DESCRIPTOR' : _LOGIN_RESPONSE,
  '__module__' : 'protos.bike_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.login_response)
  })
_sym_db.RegisterMessage(login_response)

unlock_request = _reflection.GeneratedProtocolMessageType('unlock_request', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCK_REQUEST,
  '__module__' : 'protos.bike_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.unlock_request)
  })
_sym_db.RegisterMessage(unlock_request)

unlock_response = _reflection.GeneratedProtocolMessageType('unlock_response', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCK_RESPONSE,
  '__module__' : 'protos.bike_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.unlock_response)
  })
_sym_db.RegisterMessage(unlock_response)


# @@protoc_insertion_point(module_scope)
